### PR TITLE
Removed Go 1.5 from the Travis tests

### PR DESCRIPTION
**Pull request by ijsnellf**
We don't need to support Go 1.5. Running tests for Go 1.5 slows down our Travis tests, which in turn increases the probability that developers might ignore them and push bad code.

### CODE REVIEW

**Comment by rshriram** [comment]
@zcahana any concerns? I agree with @ijsnellf that we don't need Go 1.5 in travis.

**Comment by zcahana** [comment]
I agree as well, there's no particular reason to support Go 1.5, given that we're not targeting this as library code.

Keep in mind though that this isn't expected to shorten the build much, as the 1.5/1.6 jobs are run in parallel by Travis. What might have slowed down the build is our recent move to run the builds in VMs instead of docker containers - which is required for building/pushing to Docker Hub.

**Comment by zcahana** [comment]
@ijsnellf I've added another commit to further cleanup go 1.5 related stuff. I'll mirror that to the controller/registry repo's as well.

**Comment by zcahana** [comment]
Ooops, my first commit undo'ed your changes (how did that happen?! :) ).
Anyway, my second commit is the proper one. Let's make sure all commits here are squashed before merging.

**Pull request merged**
